FROM node:latest
RUN apt update && \
    apt upgrade -y && \
    apt clean all -y && \
    apt autoclean -y && \
    apt install update-manager-core -y && \
    do-release-upgrade -d -f DistUpgradeViewNonInteractive && \
    apt clean all -y && \
    apt autoclean -y